# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhongyiyuan/My_code_csu/Gravity_Inversion_codes/GraAda3D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhongyiyuan/My_code_csu/Gravity_Inversion_codes/GraAda3D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhongyiyuan/My_code_csu/Gravity_Inversion_codes/GraAda3D/CMakeFiles /home/zhongyiyuan/My_code_csu/Gravity_Inversion_codes/GraAda3D//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhongyiyuan/My_code_csu/Gravity_Inversion_codes/GraAda3D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Forward_obj

# Build rule for target.
Forward_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Forward_obj
.PHONY : Forward_obj

# fast build rule for target.
Forward_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/build
.PHONY : Forward_obj/fast

#=============================================================================
# Target rules for targets named Inversion_obj

# Build rule for target.
Inversion_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Inversion_obj
.PHONY : Inversion_obj

# fast build rule for target.
Inversion_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/build
.PHONY : Inversion_obj/fast

#=============================================================================
# Target rules for targets named GraAda3D

# Build rule for target.
GraAda3D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraAda3D
.PHONY : GraAda3D

# fast build rule for target.
GraAda3D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraAda3D.dir/build.make CMakeFiles/GraAda3D.dir/build
.PHONY : GraAda3D/fast

#=============================================================================
# Target rules for targets named Test_ordering

# Build rule for target.
Test_ordering: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test_ordering
.PHONY : Test_ordering

# fast build rule for target.
Test_ordering/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_ordering.dir/build.make CMakeFiles/Test_ordering.dir/build
.PHONY : Test_ordering/fast

src/Forward_modelling/Cell.o: src/Forward_modelling/Cell.cpp.o
.PHONY : src/Forward_modelling/Cell.o

# target to build an object file
src/Forward_modelling/Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Cell.cpp.o
.PHONY : src/Forward_modelling/Cell.cpp.o

src/Forward_modelling/Cell.i: src/Forward_modelling/Cell.cpp.i
.PHONY : src/Forward_modelling/Cell.i

# target to preprocess a source file
src/Forward_modelling/Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Cell.cpp.i
.PHONY : src/Forward_modelling/Cell.cpp.i

src/Forward_modelling/Cell.s: src/Forward_modelling/Cell.cpp.s
.PHONY : src/Forward_modelling/Cell.s

# target to generate assembly for a file
src/Forward_modelling/Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Cell.cpp.s
.PHONY : src/Forward_modelling/Cell.cpp.s

src/Forward_modelling/Face.o: src/Forward_modelling/Face.cpp.o
.PHONY : src/Forward_modelling/Face.o

# target to build an object file
src/Forward_modelling/Face.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Face.cpp.o
.PHONY : src/Forward_modelling/Face.cpp.o

src/Forward_modelling/Face.i: src/Forward_modelling/Face.cpp.i
.PHONY : src/Forward_modelling/Face.i

# target to preprocess a source file
src/Forward_modelling/Face.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Face.cpp.i
.PHONY : src/Forward_modelling/Face.cpp.i

src/Forward_modelling/Face.s: src/Forward_modelling/Face.cpp.s
.PHONY : src/Forward_modelling/Face.s

# target to generate assembly for a file
src/Forward_modelling/Face.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Face.cpp.s
.PHONY : src/Forward_modelling/Face.cpp.s

src/Forward_modelling/Fwd.o: src/Forward_modelling/Fwd.cpp.o
.PHONY : src/Forward_modelling/Fwd.o

# target to build an object file
src/Forward_modelling/Fwd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Fwd.cpp.o
.PHONY : src/Forward_modelling/Fwd.cpp.o

src/Forward_modelling/Fwd.i: src/Forward_modelling/Fwd.cpp.i
.PHONY : src/Forward_modelling/Fwd.i

# target to preprocess a source file
src/Forward_modelling/Fwd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Fwd.cpp.i
.PHONY : src/Forward_modelling/Fwd.cpp.i

src/Forward_modelling/Fwd.s: src/Forward_modelling/Fwd.cpp.s
.PHONY : src/Forward_modelling/Fwd.s

# target to generate assembly for a file
src/Forward_modelling/Fwd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Fwd.cpp.s
.PHONY : src/Forward_modelling/Fwd.cpp.s

src/Forward_modelling/GravFormula.o: src/Forward_modelling/GravFormula.cpp.o
.PHONY : src/Forward_modelling/GravFormula.o

# target to build an object file
src/Forward_modelling/GravFormula.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/GravFormula.cpp.o
.PHONY : src/Forward_modelling/GravFormula.cpp.o

src/Forward_modelling/GravFormula.i: src/Forward_modelling/GravFormula.cpp.i
.PHONY : src/Forward_modelling/GravFormula.i

# target to preprocess a source file
src/Forward_modelling/GravFormula.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/GravFormula.cpp.i
.PHONY : src/Forward_modelling/GravFormula.cpp.i

src/Forward_modelling/GravFormula.s: src/Forward_modelling/GravFormula.cpp.s
.PHONY : src/Forward_modelling/GravFormula.s

# target to generate assembly for a file
src/Forward_modelling/GravFormula.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/GravFormula.cpp.s
.PHONY : src/Forward_modelling/GravFormula.cpp.s

src/Forward_modelling/Integral.o: src/Forward_modelling/Integral.cpp.o
.PHONY : src/Forward_modelling/Integral.o

# target to build an object file
src/Forward_modelling/Integral.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Integral.cpp.o
.PHONY : src/Forward_modelling/Integral.cpp.o

src/Forward_modelling/Integral.i: src/Forward_modelling/Integral.cpp.i
.PHONY : src/Forward_modelling/Integral.i

# target to preprocess a source file
src/Forward_modelling/Integral.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Integral.cpp.i
.PHONY : src/Forward_modelling/Integral.cpp.i

src/Forward_modelling/Integral.s: src/Forward_modelling/Integral.cpp.s
.PHONY : src/Forward_modelling/Integral.s

# target to generate assembly for a file
src/Forward_modelling/Integral.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Integral.cpp.s
.PHONY : src/Forward_modelling/Integral.cpp.s

src/Forward_modelling/Mesh.o: src/Forward_modelling/Mesh.cpp.o
.PHONY : src/Forward_modelling/Mesh.o

# target to build an object file
src/Forward_modelling/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Mesh.cpp.o
.PHONY : src/Forward_modelling/Mesh.cpp.o

src/Forward_modelling/Mesh.i: src/Forward_modelling/Mesh.cpp.i
.PHONY : src/Forward_modelling/Mesh.i

# target to preprocess a source file
src/Forward_modelling/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Mesh.cpp.i
.PHONY : src/Forward_modelling/Mesh.cpp.i

src/Forward_modelling/Mesh.s: src/Forward_modelling/Mesh.cpp.s
.PHONY : src/Forward_modelling/Mesh.s

# target to generate assembly for a file
src/Forward_modelling/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Mesh.cpp.s
.PHONY : src/Forward_modelling/Mesh.cpp.s

src/Forward_modelling/Observation.o: src/Forward_modelling/Observation.cpp.o
.PHONY : src/Forward_modelling/Observation.o

# target to build an object file
src/Forward_modelling/Observation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Observation.cpp.o
.PHONY : src/Forward_modelling/Observation.cpp.o

src/Forward_modelling/Observation.i: src/Forward_modelling/Observation.cpp.i
.PHONY : src/Forward_modelling/Observation.i

# target to preprocess a source file
src/Forward_modelling/Observation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Observation.cpp.i
.PHONY : src/Forward_modelling/Observation.cpp.i

src/Forward_modelling/Observation.s: src/Forward_modelling/Observation.cpp.s
.PHONY : src/Forward_modelling/Observation.s

# target to generate assembly for a file
src/Forward_modelling/Observation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Observation.cpp.s
.PHONY : src/Forward_modelling/Observation.cpp.s

src/Forward_modelling/Point.o: src/Forward_modelling/Point.cpp.o
.PHONY : src/Forward_modelling/Point.o

# target to build an object file
src/Forward_modelling/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Point.cpp.o
.PHONY : src/Forward_modelling/Point.cpp.o

src/Forward_modelling/Point.i: src/Forward_modelling/Point.cpp.i
.PHONY : src/Forward_modelling/Point.i

# target to preprocess a source file
src/Forward_modelling/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Point.cpp.i
.PHONY : src/Forward_modelling/Point.cpp.i

src/Forward_modelling/Point.s: src/Forward_modelling/Point.cpp.s
.PHONY : src/Forward_modelling/Point.s

# target to generate assembly for a file
src/Forward_modelling/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/Point.cpp.s
.PHONY : src/Forward_modelling/Point.cpp.s

src/Forward_modelling/RectPrism.o: src/Forward_modelling/RectPrism.cpp.o
.PHONY : src/Forward_modelling/RectPrism.o

# target to build an object file
src/Forward_modelling/RectPrism.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/RectPrism.cpp.o
.PHONY : src/Forward_modelling/RectPrism.cpp.o

src/Forward_modelling/RectPrism.i: src/Forward_modelling/RectPrism.cpp.i
.PHONY : src/Forward_modelling/RectPrism.i

# target to preprocess a source file
src/Forward_modelling/RectPrism.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/RectPrism.cpp.i
.PHONY : src/Forward_modelling/RectPrism.cpp.i

src/Forward_modelling/RectPrism.s: src/Forward_modelling/RectPrism.cpp.s
.PHONY : src/Forward_modelling/RectPrism.s

# target to generate assembly for a file
src/Forward_modelling/RectPrism.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Forward_obj.dir/build.make CMakeFiles/Forward_obj.dir/src/Forward_modelling/RectPrism.cpp.s
.PHONY : src/Forward_modelling/RectPrism.cpp.s

src/GraAda3D.o: src/GraAda3D.cpp.o
.PHONY : src/GraAda3D.o

# target to build an object file
src/GraAda3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraAda3D.dir/build.make CMakeFiles/GraAda3D.dir/src/GraAda3D.cpp.o
.PHONY : src/GraAda3D.cpp.o

src/GraAda3D.i: src/GraAda3D.cpp.i
.PHONY : src/GraAda3D.i

# target to preprocess a source file
src/GraAda3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraAda3D.dir/build.make CMakeFiles/GraAda3D.dir/src/GraAda3D.cpp.i
.PHONY : src/GraAda3D.cpp.i

src/GraAda3D.s: src/GraAda3D.cpp.s
.PHONY : src/GraAda3D.s

# target to generate assembly for a file
src/GraAda3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraAda3D.dir/build.make CMakeFiles/GraAda3D.dir/src/GraAda3D.cpp.s
.PHONY : src/GraAda3D.cpp.s

src/Inversion/AdaptiveInversion.o: src/Inversion/AdaptiveInversion.cpp.o
.PHONY : src/Inversion/AdaptiveInversion.o

# target to build an object file
src/Inversion/AdaptiveInversion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/AdaptiveInversion.cpp.o
.PHONY : src/Inversion/AdaptiveInversion.cpp.o

src/Inversion/AdaptiveInversion.i: src/Inversion/AdaptiveInversion.cpp.i
.PHONY : src/Inversion/AdaptiveInversion.i

# target to preprocess a source file
src/Inversion/AdaptiveInversion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/AdaptiveInversion.cpp.i
.PHONY : src/Inversion/AdaptiveInversion.cpp.i

src/Inversion/AdaptiveInversion.s: src/Inversion/AdaptiveInversion.cpp.s
.PHONY : src/Inversion/AdaptiveInversion.s

# target to generate assembly for a file
src/Inversion/AdaptiveInversion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/AdaptiveInversion.cpp.s
.PHONY : src/Inversion/AdaptiveInversion.cpp.s

src/Inversion/GaussNewtonInversion.o: src/Inversion/GaussNewtonInversion.cpp.o
.PHONY : src/Inversion/GaussNewtonInversion.o

# target to build an object file
src/Inversion/GaussNewtonInversion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/GaussNewtonInversion.cpp.o
.PHONY : src/Inversion/GaussNewtonInversion.cpp.o

src/Inversion/GaussNewtonInversion.i: src/Inversion/GaussNewtonInversion.cpp.i
.PHONY : src/Inversion/GaussNewtonInversion.i

# target to preprocess a source file
src/Inversion/GaussNewtonInversion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/GaussNewtonInversion.cpp.i
.PHONY : src/Inversion/GaussNewtonInversion.cpp.i

src/Inversion/GaussNewtonInversion.s: src/Inversion/GaussNewtonInversion.cpp.s
.PHONY : src/Inversion/GaussNewtonInversion.s

# target to generate assembly for a file
src/Inversion/GaussNewtonInversion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/GaussNewtonInversion.cpp.s
.PHONY : src/Inversion/GaussNewtonInversion.cpp.s

src/Inversion/InversionBase.o: src/Inversion/InversionBase.cpp.o
.PHONY : src/Inversion/InversionBase.o

# target to build an object file
src/Inversion/InversionBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/InversionBase.cpp.o
.PHONY : src/Inversion/InversionBase.cpp.o

src/Inversion/InversionBase.i: src/Inversion/InversionBase.cpp.i
.PHONY : src/Inversion/InversionBase.i

# target to preprocess a source file
src/Inversion/InversionBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/InversionBase.cpp.i
.PHONY : src/Inversion/InversionBase.cpp.i

src/Inversion/InversionBase.s: src/Inversion/InversionBase.cpp.s
.PHONY : src/Inversion/InversionBase.s

# target to generate assembly for a file
src/Inversion/InversionBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/InversionBase.cpp.s
.PHONY : src/Inversion/InversionBase.cpp.s

src/Inversion/LinearInversion.o: src/Inversion/LinearInversion.cpp.o
.PHONY : src/Inversion/LinearInversion.o

# target to build an object file
src/Inversion/LinearInversion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/LinearInversion.cpp.o
.PHONY : src/Inversion/LinearInversion.cpp.o

src/Inversion/LinearInversion.i: src/Inversion/LinearInversion.cpp.i
.PHONY : src/Inversion/LinearInversion.i

# target to preprocess a source file
src/Inversion/LinearInversion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/LinearInversion.cpp.i
.PHONY : src/Inversion/LinearInversion.cpp.i

src/Inversion/LinearInversion.s: src/Inversion/LinearInversion.cpp.s
.PHONY : src/Inversion/LinearInversion.s

# target to generate assembly for a file
src/Inversion/LinearInversion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Inversion_obj.dir/build.make CMakeFiles/Inversion_obj.dir/src/Inversion/LinearInversion.cpp.s
.PHONY : src/Inversion/LinearInversion.cpp.s

src/Test_ordering.o: src/Test_ordering.cpp.o
.PHONY : src/Test_ordering.o

# target to build an object file
src/Test_ordering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_ordering.dir/build.make CMakeFiles/Test_ordering.dir/src/Test_ordering.cpp.o
.PHONY : src/Test_ordering.cpp.o

src/Test_ordering.i: src/Test_ordering.cpp.i
.PHONY : src/Test_ordering.i

# target to preprocess a source file
src/Test_ordering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_ordering.dir/build.make CMakeFiles/Test_ordering.dir/src/Test_ordering.cpp.i
.PHONY : src/Test_ordering.cpp.i

src/Test_ordering.s: src/Test_ordering.cpp.s
.PHONY : src/Test_ordering.s

# target to generate assembly for a file
src/Test_ordering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test_ordering.dir/build.make CMakeFiles/Test_ordering.dir/src/Test_ordering.cpp.s
.PHONY : src/Test_ordering.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Forward_obj"
	@echo "... GraAda3D"
	@echo "... Inversion_obj"
	@echo "... Test_ordering"
	@echo "... src/Forward_modelling/Cell.o"
	@echo "... src/Forward_modelling/Cell.i"
	@echo "... src/Forward_modelling/Cell.s"
	@echo "... src/Forward_modelling/Face.o"
	@echo "... src/Forward_modelling/Face.i"
	@echo "... src/Forward_modelling/Face.s"
	@echo "... src/Forward_modelling/Fwd.o"
	@echo "... src/Forward_modelling/Fwd.i"
	@echo "... src/Forward_modelling/Fwd.s"
	@echo "... src/Forward_modelling/GravFormula.o"
	@echo "... src/Forward_modelling/GravFormula.i"
	@echo "... src/Forward_modelling/GravFormula.s"
	@echo "... src/Forward_modelling/Integral.o"
	@echo "... src/Forward_modelling/Integral.i"
	@echo "... src/Forward_modelling/Integral.s"
	@echo "... src/Forward_modelling/Mesh.o"
	@echo "... src/Forward_modelling/Mesh.i"
	@echo "... src/Forward_modelling/Mesh.s"
	@echo "... src/Forward_modelling/Observation.o"
	@echo "... src/Forward_modelling/Observation.i"
	@echo "... src/Forward_modelling/Observation.s"
	@echo "... src/Forward_modelling/Point.o"
	@echo "... src/Forward_modelling/Point.i"
	@echo "... src/Forward_modelling/Point.s"
	@echo "... src/Forward_modelling/RectPrism.o"
	@echo "... src/Forward_modelling/RectPrism.i"
	@echo "... src/Forward_modelling/RectPrism.s"
	@echo "... src/GraAda3D.o"
	@echo "... src/GraAda3D.i"
	@echo "... src/GraAda3D.s"
	@echo "... src/Inversion/AdaptiveInversion.o"
	@echo "... src/Inversion/AdaptiveInversion.i"
	@echo "... src/Inversion/AdaptiveInversion.s"
	@echo "... src/Inversion/GaussNewtonInversion.o"
	@echo "... src/Inversion/GaussNewtonInversion.i"
	@echo "... src/Inversion/GaussNewtonInversion.s"
	@echo "... src/Inversion/InversionBase.o"
	@echo "... src/Inversion/InversionBase.i"
	@echo "... src/Inversion/InversionBase.s"
	@echo "... src/Inversion/LinearInversion.o"
	@echo "... src/Inversion/LinearInversion.i"
	@echo "... src/Inversion/LinearInversion.s"
	@echo "... src/Test_ordering.o"
	@echo "... src/Test_ordering.i"
	@echo "... src/Test_ordering.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

